#!/bin/bash
#----------------------------------------------------------------------------------------------------------------#
# INPUT
#----------------------------------------------------------------------------------------------------------------#
DNA_ID=$1 # number

# Add CG topology, parameters, link and patches
DNACG_FOLDER=/home/rodrigo/cg-params/

CG_TOP=$DNACG_FOLDER/dna-CG-MARTINI-2-1p.top
CG_PARAM=$DNACG_FOLDER/dna-CG-MARTINI-2-1p.param
CG_LINK=$DNACG_FOLDER/dna-CG-MARTINI-2-1p.link
CG_DNA_BREAK_TOP=$DNACG_FOLDER/dna-CG-MARTINI-2-1p-break.top

CG_HBONDS=$DNACG_FOLDER/patch-types-cg-hbond-dna.cns
CG_DNA_BREAKS=$DNACG_FOLDER/patch-breaks-cg-dna.cns


#----------------------------------------------------------------------------------------------------------------#
# SET UP CG RUN
#----------------------------------------------------------------------------------------------------------------#
echo "> Setting CG run"

echo "RUN1"
cd run1

#----------------------------------------------------------------------------------------------------------------#
# Copy new files
#----------------------------------------------------------------------------------------------------------------#
echo "> Copying DNA CG files"
# Add CG topology, parameters, link and patches
cp $CG_TOP toppar/
cp $CG_PARAM toppar/
cp $CG_LINK toppar/
cp $CG_DNA_BREAK_TOP toppar/

cp $CG_HBONDS protocols/
cp $CG_DNA_BREAKS protocols/

#----------------------------------------------------------------------------------------------------------------#
# Patch HADDOCK files
#----------------------------------------------------------------------------------------------------------------#
echo "> Patching HADDOCK files"
patch protocols/refine.inp -i $DNACG_FOLDER/refine.patch
patch protocols/generate-cg.inp -i $DNACG_FOLDER/generate-cg.patch
patch run.cns -i $DNACG_FOLDER/run.cns.patch

#----------------------------------------------------------------------------------------------------------------#
# Edit run.cns
#----------------------------------------------------------------------------------------------------------------#
echo "> Editting run.cns"

# Flag DNA molecule
sed -i "s/{===>} dna_mol$DNA_ID=false;/{===>} dna_mol$DNA_ID=true;/g" run.cns

# set AA parameters
sed -i "s/{===>} prot_top_mol$DNA_ID=\"protein-allhdg5-4.top\";/{===>} prot_top_mol$DNA_ID=\"dna-rna-allatom-hj-opls-1.3.top\";/g" run.cns
sed -i "s/{===>} prot_link_mol$DNA_ID=\"protein-allhdg5-4-noter.link\";/{===>} prot_link_mol$DNA_ID=\"dna-rna-1.3.link\";/g" run.cns
sed -i "s/{===>} prot_par_mol$DNA_ID=\"protein-allhdg5-4.param\";/{===>} prot_par_mol$DNA_ID=\"dna-rna-allatom-hj-opls-1.3.param\";/g" run.cns

# set CG parameters
sed -i "s/{===>} prot_cg_top_mol$DNA_ID=\"protein-CG-Martini-2-2.top\";/{===>} prot_cg_top_mol$DNA_ID=\"dna-CG-MARTINI-2-1p.top\";/g" run.cns
sed -i "s/{===>} prot_cg_link_mol$DNA_ID=\"protein-CG-Martini-2-2.link\";/{===>} prot_cg_link_mol$DNA_ID=\"dna-CG-MARTINI-2-1p.link\";/g" run.cns
sed -i "s/{===>} prot_cg_par_mol$DNA_ID=\"protein-CG-Martini-2-2.param\";/{===>} prot_cg_par_mol$DNA_ID=\"dna-CG-MARTINI-2-1p.param\";/g" run.cns

# Setup ProtDNA CG specific simulation parameters
sed -i 's/{===>} w_desolv_0=1.0/{===>} w_desolv_0=0.0/g' run.cns
sed -i 's/{===>} w_desolv_1=1.0/{===>} w_desolv_1=0.0/g' run.cns
sed -i 's/{===>} w_desolv_2=1.0/{===>} w_desolv_2=0.0/g' run.cns

sed -i 's/{===>} epsilon_0=10.0/{===>} epsilon_0=78.0/g' run.cns
sed -i 's/{===>} epsilon_1=1.0/{===>} epsilon_1=78.0/g' run.cns
sed -i 's/{===>} epsilon_1=10.0/{===>} epsilon_1=78.0/g' run.cns

sed -i 's/{===>} dielec_0=rdie/{===>} dielec_0=cdie/g' run.cns
sed -i 's/{===>} dielec_1=rdie/{===>} dielec_1=cdie/g' run.cns

if [ -f ../dna_restraints.def ]; then
	sed -i "s/{===>} dnacgrest_on=false/{===>} dnacgrest_on=true/g" run.cns
	sed -i "s/{===>} dnarest_on=false/{===>} dnarest_on=true/g" run.cns
fi

#----------------------------------------------------------------------------------------------------------------#
# Write DNA-AA restraints
#----------------------------------------------------------------------------------------------------------------#
echo "> Writing DNA-CG/AA restraints"
if [ -f ../dna_restraints.def ]; then
	#====#
	# The files dna-aa_groups.dat and dna_restraints.def are generated by the aa2cg-prot_dna.py script!
	#
	# template-dna-rna-aa-restraints.def and dna-cg_restraints-ori.def are edited versions of the files generated by default
	#  by HADDOCK, these two files are ready for the following edits. It will not work with any other file!
	#====#
	# add restraints to line 308 of template-dna-rna-aa-restraints.def
	sed "308r ../dna_restraints.def" $DNACG_FOLDER/template-dna-aa-restraints.def > data/sequence/dna-rna_restraints.def
	# get groups
	AAGROUP_1=$(sed -n '1p' ../dna-aa_groups.dat)
	SEGID_1=$(sed -n '2p' ../dna-aa_groups.dat) 
	AAGROUP_2=$(sed -n '3p' ../dna-aa_groups.dat)
	SEGID_2=$(sed -n '4p' ../dna-aa_groups.dat) 
	sed -i "s/{===>} bases_planar=((resid 1:20 or resid 21:40) and segid B);/{===>} bases_planar=((resid $AAGROUP_1 or resid $AAGROUP_2) and segid $SEGID_2);/g" data/sequence/dna-rna_restraints.def
	sed -i "s/{===>} pucker_1=(resid 1:20 and segid B);/{===>} pucker_1=(resid $AAGROUP_1 and segid $SEGID_1);/g" data/sequence/dna-rna_restraints.def
	sed -i "s/{===>} pucker_2=(resid 21:40 and segid B);/{===>} pucker_2=(resid $AAGROUP_2 and segid $SEGID_2);/g" data/sequence/dna-rna_restraints.def
	sed -i "s/{===>} dihedral_1=(resid 1:20 and segid B);/{===>} dihedral_1=(resid $AAGROUP_1 and segid $SEGID_1);/g" data/sequence/dna-rna_restraints.def
	sed -i "s/{===>} dihedral_2=(resid 21:40 and segid B);/{===>} dihedral_2=(resid $AAGROUP_2 and segid $SEGID_2);/g" data/sequence/dna-rna_restraints.def
	sed -i 's/{===>} basepair_planar=false;/{===>} basepair_planar=true;/g' data/sequence/dna-rna_restraints.def
	# add restraints to line 18 of template-dna-rna-aa-restraints.def
	sed "18r ../dna_restraints.def" $DNACG_FOLDER/template-dna-cg-restraints.def > data/sequence/dna-cg_restraints.def

else
	# file does not exist
	sed -i '/{===>} dnarest_on=false;/a {===>} dnacgrest_on=false;' run.cns
fi

#----------------------------------------------------------------------------------------------------------------#
echo "> ready"
cd ..